const skills = [
    "JavaScript",
    "React",
    "Node.js",
    "Python",
    "Django",
    "Flask",
    "Java",
    "Spring Boot",
    "C#",
    ".NET",
    "SQL",
    "MongoDB",
    "AWS",
    "Azure",
    "Docker",
    "Kubernetes",
    "HTML",
    "CSS",
    "TypeScript",
    "Angular",
    "Vue.js",
    "PHP",
    "Laravel",
    "Ruby",
    "Ruby on Rails",
    "Swift",
    "iOS Development",
    "Android Development",
    "Machine Learning",
    "Data Science",
    "Artificial Intelligence",
    "Cybersecurity",
    "Networking",
    "DevOps",
    "Git",
    "CI/CD",
    "UI/UX Design",
    "Graphic Design",
    "Digital Marketing",
    "SEO",
    "Content Writing",
    "Copywriting",
    "Video Editing",
    "Photography",
    "3D Modeling",
    "Animation",
    "Game Development",
    "Unity",
    "Unreal Engine",
    "Project Management",
    "Agile Methodologies",
    "Scrum",
    "Business Analysis",
    "Financial Analysis",
    "Sales",
    "Customer Service",
    "Human Resources",
    "Recruiting",
    "Public Speaking",
    "Leadership",
    "Time Management",
    "Problem Solving",
    "Critical Thinking",
    "Communication Skills",
    "Teamwork",
    "Negotiation",
    "Presentation Skills",
  ];
  
  export default skills;
  